version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - shared-volume:/etc/nginx/streams.d
    ports:
      - "8080:80"       

  nginx-lb-updater:
    image: quay.io/didil/nginx-lb-updater:6e0f56d
    ports:
      - "3000:3000"    
    volumes:
      #- /host/path/nginx.conf:/etc/nginx/nginx.conf:ro
      - shared-volume:/etc/nginx/streams.d

volumes:
  shared-volume: