version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - shared-volume:/etc/nginx/streams.d
    ports:
      - "8080:8080"       

  nginx-lb-updater:
    build: .
    ports:
      - "3000:3000"    
    volumes:
      - shared-volume:/etc/nginx/streams.d

volumes:
  shared-volume: