version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - shared-volume:/etc/nginx/streams.d

  nginx-lb-updater:
    image: quay.io/didil/nginx-lb-updater  
    volumes:
      #- /host/path/nginx.conf:/etc/nginx/nginx.conf:ro
      - shared-volume:/etc/nginx/streams.d


volumes:
  shared-volume: