version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - shared-volume:/etc/nginx/streams.d
    ports:
      - "8100:8100"       
      - "8101:8101"       
      - "8102:8102"       
      - "8103:8103"       
      - "8104:8104"       

  nginx-lb-updater:
    build: .
    ports:
      - "3000:3000"    
    volumes:
      - shared-volume:/etc/nginx/streams.d

volumes:
  shared-volume: